create_pr_dw = '''


-- Table DIM_Productos

DROP TABLE IF EXISTS DIM_Productos CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Productos (
Producto_FK SERIAL PRIMARY KEY,
Cod_INE VARCHAR(45) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Especificaciones TEXT NOT NULL,
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT Cod_INE_UNIQUE UNIQUE (Cod_INE)
);

-- Table DIM_Proveedor

DROP TABLE IF EXISTS DIM_Proveedor CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Proveedor (
Proveedor_FK SERIAL PRIMARY KEY,
NIT INTEGER NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Direccion VARCHAR(255),
"Teléfono" VARCHAR(45),
"e-mail" VARCHAR(45),
Comentarios TEXT,
Sector VARCHAR(45) NOT NULL,
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT NIT_UNIQUE UNIQUE (NIT)
);

-- Table DIM_Fuente

DROP TABLE IF EXISTS DIM_Fuente CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Fuente (
Fuente_FK SERIAL PRIMARY KEY,
FuenteDatos VARCHAR(45) NOT NULL,
timestamp TIMESTAMP DEFAULT NULL
);

-- Table DIM_Rubro

DROP TABLE IF EXISTS DIM_Rubro CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Rubro (
Rubro_FK SERIAL PRIMARY KEY,
Rubro VARCHAR(45) NOT NULL,
timestamp TIMESTAMP DEFAULT NULL
);

-- Table DIM_Medida

DROP TABLE IF EXISTS DIM_Medida CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Medida (
Medida_FK SERIAL PRIMARY KEY,
UnidadMedida VARCHAR(45) NOT NULL,
Tipo VARCHAR(45) NOT NULL,
Dimensional VARCHAR(10),
timestamp TIMESTAMP DEFAULT NULL
);

-- Table DIM_Entidad

DROP TABLE IF EXISTS DIM_Entidad CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Entidad (
Entidad_FK SERIAL PRIMARY KEY,
Nombre VARCHAR(45) NOT NULL,
Tipo VARCHAR(45),
Sub_Tipo VARCHAR(45),
Unidad_Compradora VARCHAR(45),
timestamp TIMESTAMP DEFAULT NULL
);

-- Table DIM_Date

DROP TABLE IF EXISTS DIM_Date CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Date (
Date_key SERIAL PRIMARY KEY,
Fecha DATE,
Mes VARCHAR(45),
Año INTEGER,
Mes_Año VARCHAR(45),
"Fecha +40d" DATE
);

-- Table DIM_Adquisicion

DROP TABLE IF EXISTS DIM_Adquisicion CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Adquisicion (
Adquisicion_FK SERIAL PRIMARY KEY,
Tipo_Adquisicion VARCHAR(45) NOT NULL,
timestamp TIMESTAMP NOT NULL DEFAULT now()
);

-- Table DIM_Divisas

DROP TABLE IF EXISTS DIM_Divisas CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Divisas (
Divisa_FK SERIAL PRIMARY KEY,
Divisa VARCHAR(45),
Abreviatura VARCHAR(5),
"Símbolo" VARCHAR(5),
timestamp TIMESTAMP DEFAULT now()
);

-- Table FACT_Precio

DROP TABLE IF EXISTS FACT_Precio CASCADE;

CREATE TABLE IF NOT EXISTS FACT_Precio (
Precio_ID SERIAL,
Producto_FK INT NOT NULL,
Proveedor_FK INT NOT NULL,
Fuente_FK INT NOT NULL,
Medida_FK INT NOT NULL,
Date_key INT NOT NULL,
Divisa_FK INT NOT NULL,
Precio DECIMAL(10) NOT NULL,
Marca VARCHAR(45),
Pais VARCHAR(45),
NOG VARCHAR(45),
Responsable VARCHAR(45),
Observaciones TEXT,
timestamp TIMESTAMP NOT NULL DEFAULT now(),
PRIMARY KEY (Precio_ID, Producto_FK, Proveedor_FK, Fuente_FK, Medida_FK),
CONSTRAINT ProductoPrecio
FOREIGN KEY (Producto_FK)
REFERENCES DIM_Productos (Producto_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT ProveedorPrecio
FOREIGN KEY (Proveedor_FK)
REFERENCES DIM_Proveedor (Proveedor_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FuentePrecio
FOREIGN KEY (Fuente_FK)
REFERENCES DIM_Fuente (Fuente_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT MedidaPrecio
FOREIGN KEY (Medida_FK)
REFERENCES DIM_Medida (Medida_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FechaPrecio
FOREIGN KEY (Date_key)
REFERENCES DIM_Date (Date_key)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT DivisaPrecio
FOREIGN KEY (Divisa_FK)
REFERENCES DIM_Divisas (Divisa_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

-- Table DIM_Evento

DROP TABLE IF EXISTS DIM_Evento CASCADE;

CREATE TABLE IF NOT EXISTS DIM_Evento (
Evento_FK INT NOT NULL,
NOG INT NOT NULL,
Nombre VARCHAR(255) NULL,
Enlace VARCHAR(45) NULL,
Entidad INT NOT NULL,
Adquisición_FK INT NOT NULL,
Date_Key INT NOT NULL,
PRIMARY KEY (Evento_FK),
CONSTRAINT Date_Evento
FOREIGN KEY (Date_Key)
REFERENCES DIM_Date(Date_key)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT Entidad_Evento
FOREIGN KEY (Entidad)
REFERENCES DIM_Entidad(Entidad_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT Adquisicion_Evento
FOREIGN KEY (Adquisición_FK)
REFERENCES DIM_Adquisicion(Adquisicion_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE INDEX Date_Evento_idx ON DIM_Evento (Date_Key);
CREATE INDEX Entidad_Evento_idx ON DIM_Evento (Entidad);
CREATE INDEX Adquisicion_Evento_idx ON DIM_Evento (Adquisición_FK);

-- Table FACT_Catalogo

DROP TABLE IF EXISTS FACT_Catalogo CASCADE;

CREATE TABLE IF NOT EXISTS FACT_Catalogo (
Catalogo_ID SERIAL PRIMARY KEY,
Revision INT NOT NULL,
Evento_FK INT NOT NULL,
Renglon INT NOT NULL,
Producto_FK INT NOT NULL,
Medida_FK INT NOT NULL,
Cantidad INT NULL,
Rubro_FK INT NOT NULL,
timestamp TIMESTAMP NULL DEFAULT NOW(),
PR DECIMAL(10,2) NULL,
Date_key INT NULL,
Observaciones VARCHAR(45) NULL,
CONSTRAINT EventoProducto
FOREIGN KEY (Producto_FK)
REFERENCES DIM_Productos (Producto_FK)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT EventoRubro
FOREIGN KEY (Rubro_FK)
REFERENCES DIM_Rubro (Rubro_FK)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT EventoMedida
FOREIGN KEY (Medida_FK)
REFERENCES DIM_Medida (Medida_FK)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT EventoCatalogo
FOREIGN KEY (Evento_FK)
REFERENCES DIM_Evento (Evento_FK)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE INDEX EventoProducto_idx ON FACT_Catalogo (Producto_FK);
CREATE INDEX EventoRubro_idx ON FACT_Catalogo (Rubro_FK);
CREATE INDEX EventoMedida_idx ON FACT_Catalogo (Medida_FK);
CREATE INDEX EventoCatalogo_idx ON FACT_Catalogo (Evento_FK);

'''